# Generated by Django 4.2.2 on 2026-03-11 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albaranes',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('num_albaran', models.IntegerField(unique=True)),
                ('fecha_albaran', models.DateField()),
                ('num_pedidos_incluidos', models.CharField(default='', max_length=70)),
                ('direccion_calle_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_piso', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion_localidad', models.CharField(blank=True, max_length=40, null=True)),
                ('direccion_cp', models.CharField(blank=True, max_length=20, null=True)),
                ('cif_vat', models.CharField(blank=True, max_length=30, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('bultos', models.IntegerField()),
                ('medidas', models.CharField(blank=True, max_length=100)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=100, unique=True)),
                ('direccion_calle_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_piso', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion_localidad', models.CharField(blank=True, max_length=40, null=True)),
                ('direccion_cp', models.CharField(blank=True, max_length=20, null=True)),
                ('cif_vat', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('otros_datos1', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('num_factura', models.IntegerField(unique=True)),
                ('fecha_factura', models.DateField()),
                ('num_pedidos_incluidos', models.CharField(default='', max_length=70)),
                ('direccion_calle_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_piso', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion_localidad', models.CharField(blank=True, max_length=40, null=True)),
                ('direccion_cp', models.CharField(blank=True, max_length=20, null=True)),
                ('cif_vat', models.CharField(blank=True, max_length=30, null=True)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('packaging', models.CharField(blank=True, max_length=60, null=True)),
                ('iva', models.DecimalField(decimal_places=3, max_digits=10)),
                ('dias_transferencia', models.IntegerField()),
                ('fecha_limite_transferencia', models.DateField(blank=True, null=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.clientes', to_field='cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Incoterms',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('incoterms', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monedas',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('moneda', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('pais', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('num_pedido', models.IntegerField(unique=True)),
                ('id_cliente', models.IntegerField(blank=True, null=True)),
                ('tipo_cliente', models.CharField(blank=True, default='', max_length=50)),
                ('fecha', models.DateField()),
                ('precio_total', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_cliente_reverse', to='tienda.clientes', to_field='cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('codigo_articulo', models.CharField(max_length=25, unique=True)),
                ('descripcion', models.CharField(max_length=150, unique=True)),
                ('precioTipo1', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precioTipo2', models.DecimalField(decimal_places=3, max_digits=10)),
                ('precioTipo3', models.DecimalField(decimal_places=3, max_digits=10)),
                ('peso_neto', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transportistas',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos_Lineas',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cliente', models.CharField(blank=True, default='', max_length=100)),
                ('tipo_cliente', models.CharField(blank=True, default='', max_length=50)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('precio_total_linea', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('precio_total_pedido', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cantidad_servida', models.IntegerField(default=0)),
                ('cantidad_facturada', models.IntegerField(default=0)),
                ('cerrado', models.BooleanField(default=False)),
                ('codigo_articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.productos', to_field='codigo_articulo')),
                ('num_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.pedidos', to_field='num_pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas_lineas',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('identificador_linea_pedido', models.IntegerField(blank=True, null=True)),
                ('codigo_articulo', models.CharField(max_length=25)),
                ('cantidad_total', models.IntegerField()),
                ('cantidad_facturada', models.IntegerField()),
                ('precio_unitario_linea_pedido', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('cliente', models.CharField(blank=True, default='', max_length=100)),
                ('num_factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.facturas', to_field='num_factura')),
                ('num_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.pedidos', to_field='num_pedido')),
            ],
        ),
        migrations.AddField(
            model_name='facturas',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.monedas', to_field='moneda'),
        ),
        migrations.AddField(
            model_name='facturas',
            name='transportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.transportistas', to_field='nombre'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.paises', to_field='pais'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='tipo_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.tipoclientes'),
        ),
        migrations.CreateModel(
            name='Albaranes_lineas',
            fields=[
                ('identificador', models.AutoField(primary_key=True, serialize=False)),
                ('identificador_linea_pedido', models.IntegerField(blank=True, null=True)),
                ('codigo_articulo', models.CharField(max_length=25)),
                ('cantidad_total', models.IntegerField()),
                ('cantidad_servida', models.IntegerField()),
                ('cliente', models.CharField(blank=True, default='', max_length=100)),
                ('peso_neto', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('num_albaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tienda.albaranes', to_field='num_albaran')),
                ('num_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.pedidos', to_field='num_pedido')),
            ],
        ),
        migrations.AddField(
            model_name='albaranes',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.clientes', to_field='cliente'),
        ),
        migrations.AddField(
            model_name='albaranes',
            name='incoterms',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.incoterms', to_field='incoterms'),
        ),
        migrations.AddField(
            model_name='albaranes',
            name='transportista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.transportistas', to_field='nombre'),
        ),
    ]
